files:
  # Include specific files and directories necessary for the project
  - "CMakeLists.txt"
  - "cmake/*.cmake"
  - "include/**/*.h"
  - "PluginTemplate/**/*"
  - "vendor/imgui/**/*"
  - ".clang-tidy"
  - ".clang-format"
  - ".gitmodules"
  - "info.xml.in"
  - ".github/workflows/**/*"
  - "!.github/workflows/template-sync.yml" # Exclude the workflow file itself

  # Exclude files and directories that are not necessary or are generated
  - "!cmake-build-debug/**/*"
  - "!build/**/*"
  - "!**/.git/**"
  - "!**/.idea/**"
  - "!PluginTemplate/cmake-build-debug/**/*"

  # Specific exclusions as per .gitignore
  - "!@OUT"
  - "!PluginTemplate/cmake-build-debug/"
  - "!/build/"
  - "!/cmake-build-debug/"
