name: template-sync

on: [push, pull_request, workflow_dispatch]

jobs:
  template-sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: euphoricsystems/action-sync-template-repository@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
